_commit: v1.5.1
_src_path: gh:superlinear-ai/substrate
author_email: info@chatmangpt.com
author_name: Sean Chatman
project_description: Weaver Forge Generation
project_name: WeaverGen v2
project_type: app
project_url: https://github.com/seanchatmangpt/wvrgen
python_version: '3.12'
typing: optional
with_conventional_commits: true
with_fastapi_api: false
with_typer_cli: true
